// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCskU1QihiT1B7w3_X88WpVvPkJQAdYmF0',
    appId: '1:787739951920:web:7228df718368f128a33ef5',
    messagingSenderId: '787739951920',
    projectId: 'coffee-shop-ai',
    authDomain: 'coffee-shop-ai.firebaseapp.com',
    storageBucket: 'coffee-shop-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5b-FFG6zPtsg3zZV9pVzk802lKy6HxCc',
    appId: '1:787739951920:android:bbc9ab94b18b637ba33ef5',
    messagingSenderId: '787739951920',
    projectId: 'coffee-shop-ai',
    storageBucket: 'coffee-shop-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz47v59OU-VqmLfj_qnBYbuGUABRrydi0',
    appId: '1:787739951920:ios:5e22f2ee21a9f511a33ef5',
    messagingSenderId: '787739951920',
    projectId: 'coffee-shop-ai',
    storageBucket: 'coffee-shop-ai.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShopAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz47v59OU-VqmLfj_qnBYbuGUABRrydi0',
    appId: '1:787739951920:ios:5e22f2ee21a9f511a33ef5',
    messagingSenderId: '787739951920',
    projectId: 'coffee-shop-ai',
    storageBucket: 'coffee-shop-ai.firebasestorage.app',
    iosBundleId: 'com.example.coffeeShopAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCskU1QihiT1B7w3_X88WpVvPkJQAdYmF0',
    appId: '1:787739951920:web:a400750b327ed925a33ef5',
    messagingSenderId: '787739951920',
    projectId: 'coffee-shop-ai',
    authDomain: 'coffee-shop-ai.firebaseapp.com',
    storageBucket: 'coffee-shop-ai.firebasestorage.app',
  );
}
